### PR TITLE
Added selectors to detail object of destroy event. 

### PR DESCRIPTION
**Pull request by pirkka**
Now you can determine which grid(s) triggered the event.

### CODE REVIEW

**Comment by attila** [comment]
Thanks for this. Can you add the change to the relevant source file so that the build and tests run too?

**Comment by pirkka** [comment]
okay, first time doing this so I fumbled a little bit but now it should be in working order.

**Comment by pirkka** [comment]
not sure if i should only have submitted the src changes and nothing in the dist folder... i can do another PR if that's better <:

**Comment by attila** [comment]
Looks a lot better, thanks. Never mind the dist changes it comes from the fact that there has not been a release for a while :( As long as the change is recorded in src then the tests will run on the new version.
Speaking of which, could you maybe extend the [test case](https://github.com/taeggie/savvior/blob/91d8a7080a44565a863ada70c3176c8115c61144/tests/GridDispatchSpec.js#L171) so it checks for the passed selectors in the event?

**Comment by attila** [comment]
No worries, added the missing unit test in https://github.com/attila/savvior/commit/9c9131e90de36ccaf81628787658751374e041aa

Many thanks again for the PR! 👍

**Pull request merged**
